# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: config.toml
# purpose: Bootstrap configuration
# ---------------------------------------------------------------------------

[database]
database_file = "{$app}/test/model_archivist.db"

[web]
host = "127.0.0.1"
port = 5173
static_html = "{$app}/frontend/build"

[logging]
level = "DEBUG"
sql_level = "WARNING"
file = "{$app}/archivist.log"
