# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: pyproject.toml
# purpose: Python package metadata and Comfy Registry publication configuration
# ---------------------------------------------------------------------------

[build-system]
requires = ["setuptools >= 80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyui-model-archivist"
version = "1.0.0"
requires-python = ">= 3.12"
description = "Organize, archive, and synchronize models, workflows, and user-defined files in ComfyUI or as a standalone application."
readme = "README.md"
authors = [{name="Tumbislav Nilski"}]
license = "GPL-3.0-or-later"
license-files = ["LICENSE.md"]
dependencies = [
    "aiohttp >= 3.11.0",
    "alembic >= 1.17.2",
    "fastapi >= 0.124.4",
    "pydantic >= 2.10.0",
    "sqlalchemy >= 2.0.0",
    "sqlmodel >= 0.0.27",
    "uvicorn >= 0.40.0"
]

[project.optional-dependencies]
dev = [
    "pytest >= 9.0.2"
]

[project.urls]
Repository = "https://github.com/tumbislav/ComfyUI-ModelArchivist"
Documentation = "https://github.com/tumbislav/ComfyUI-ModelArchivist#readme"
Issues = "https://github.com/tumbislav/ComfyUI-ModelArchivist/issues"

[tool.setuptools.packages.find]
include = ["backend*"]

[tool.comfy]
PublisherId = "tumbislav-nilski"
DisplayName = "Model Archivist"
includes = ["frontend/build"]
