# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: 2026_08_30_0959-000000000001_baseline.py
# purpose: Baseline database schema
# ---------------------------------------------------------------------------

"""baseline

Revision ID: 000000000001
Revises: 
Create Date: 2026-08-30 09:59:38.323758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '000000000001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicationsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setup_complete', sa.Boolean(), nullable=False),
    sa.Column('update_json_metadata', sa.Boolean(), nullable=False),
    sa.Column('ignore_unknown_types', sa.Boolean(), nullable=False),
    sa.Column('always_recalc_hashes', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modeltypesetting',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extensions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tag',
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('userdefinedtype',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sa.String(collation='NOCASE'), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extensions', sa.JSON(), nullable=False),
    sa.Column('working_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archive_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_limit', sa.Integer(), nullable=False),
    sa.Column('small', sa.Boolean(), nullable=False),
    sa.CheckConstraint("object_class IN ('file', 'folder')"),
    sa.CheckConstraint('size_limit > 0'),
    sa.CheckConstraint('small = 0 OR size_limit <= 1048576'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archive_dir'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('working_dir')
    )
    op.create_table('workflow',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflowlocationsetting',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('working_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archive_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archive_dir'),
    sa.UniqueConstraint('working_dir')
    )
    op.create_table('collectioncollectionlink',
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('componentset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('where', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examples_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('"where" IN (\'w\', \'a\')'),
    sa.CheckConstraint('(model_id IS NOT NULL AND workflow_id IS NULL) OR (model_id IS NULL AND workflow_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'where'),
    sa.UniqueConstraint('workflow_id', 'where')
    )
    op.create_table('modelcollectionlink',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'collection_id')
    )
    op.create_table('modellocationsetting',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('working_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archive_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_type'], ['modeltypesetting.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archive_dir'),
    sa.UniqueConstraint('working_dir')
    )
    op.create_table('tagcollectionlink',
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.PrimaryKeyConstraint('collection_id', 'tag')
    )
    op.create_table('tagmodellink',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.PrimaryKeyConstraint('model_id', 'tag')
    )
    op.create_table('tagworkflowlink',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('workflow_id', 'tag')
    )
    op.create_table('userdefinedobject',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('modified_at_ns', sa.Integer(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['userdefinedtype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'relative_path')
    )
    op.create_table('workflowcollectionlink',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('workflow_id', 'collection_id')
    )
    op.create_table('component',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('modified_at_ns', sa.Integer(), nullable=False),
    sa.Column('component_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['component_set_id'], ['componentset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taguserobjectlink',
    sa.Column('user_object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.ForeignKeyConstraint(['user_object_id'], ['userdefinedobject.id'], ),
    sa.PrimaryKeyConstraint('user_object_id', 'tag')
    )
    op.create_table('userobjectcollectionlink',
    sa.Column('user_object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['user_object_id'], ['userdefinedobject.id'], ),
    sa.PrimaryKeyConstraint('user_object_id', 'collection_id')
    )
    op.create_table('userobjectset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('where', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('modified_at_ns', sa.Integer(), nullable=False),
    sa.CheckConstraint('"where" IN (\'w\', \'a\')'),
    sa.ForeignKeyConstraint(['object_id'], ['userdefinedobject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'where')
    )
    op.create_table('userobjectentry',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('modified_at_ns', sa.Integer(), nullable=False),
    sa.CheckConstraint("entry_type IN ('file', 'directory')"),
    sa.ForeignKeyConstraint(['object_set_id'], ['userobjectset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_set_id', 'relative_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userobjectentry')
    op.drop_table('userobjectset')
    op.drop_table('userobjectcollectionlink')
    op.drop_table('taguserobjectlink')
    op.drop_table('component')
    op.drop_table('workflowcollectionlink')
    op.drop_table('userdefinedobject')
    op.drop_table('tagworkflowlink')
    op.drop_table('tagmodellink')
    op.drop_table('tagcollectionlink')
    op.drop_table('modellocationsetting')
    op.drop_table('modelcollectionlink')
    op.drop_table('componentset')
    op.drop_table('collectioncollectionlink')
    op.drop_table('workflowlocationsetting')
    op.drop_table('workflow')
    op.drop_table('userdefinedtype')
    op.drop_table('tag')
    op.drop_table('modeltypesetting')
    op.drop_table('model')
    op.drop_table('collection')
    op.drop_table('applicationsettings')
    # ### end Alembic commands ###
