# ---------------------------------------------------------------------------
# system: ModelArchivist
# file: 2026_08_22_1728-16da8f3ac79c_initial_schema.py
# purpose: Alembic baseline for the initial database schema
# ---------------------------------------------------------------------------

"""initial schema

Revision ID: 16da8f3ac79c
Revises: 
Create Date: 2026-08-22 17:28:45.565358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16da8f3ac79c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('workflow',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('internal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deployment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collectioncollectionlink',
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('componentset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('where', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examples_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("\"where\" IN ('w', 'a')"),
    sa.CheckConstraint('(model_id IS NOT NULL AND workflow_id IS NULL) OR (model_id IS NULL AND workflow_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'where'),
    sa.UniqueConstraint('workflow_id', 'where')
    )
    op.create_table('modelcollectionlink',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'collection_id')
    )
    op.create_table('tagcollectionlink',
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.PrimaryKeyConstraint('collection_id', 'tag')
    )
    op.create_table('tagmodellink',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.PrimaryKeyConstraint('model_id', 'tag')
    )
    op.create_table('tagworkflowlink',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tag'], ['tag.tag'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('workflow_id', 'tag')
    )
    op.create_table('workflowcollectionlink',
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('workflow_id', 'collection_id')
    )
    op.create_table('component',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('touched', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('component_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['component_set_id'], ['componentset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component')
    op.drop_table('workflowcollectionlink')
    op.drop_table('tagworkflowlink')
    op.drop_table('tagmodellink')
    op.drop_table('tagcollectionlink')
    op.drop_table('modelcollectionlink')
    op.drop_table('componentset')
    op.drop_table('collectioncollectionlink')
    op.drop_table('workflow')
    op.drop_table('tag')
    op.drop_table('model')
    op.drop_table('collection')
    # ### end Alembic commands ###
